import type {
  Season,
  League,
  Team,
  Round,
  TeamStanding,
  NewsItem,
  ArchiveSeason,
} from "./types/app";

export const MOCK_SEASON: Season = {
  id: "season-1",
  name: "FSL Season 1",
  status: "active",
  startDate: "2026-03-01",
  endDate: "2026-08-31",
  description: "福岡スーパーリーグ 第1シーズン",
  heroImageUrl: null,
  heroVideoUrl: null,
  youtubePlaylistId: "PLxxxxxxxxxxxxxxxx",
};

export const MOCK_LEAGUES: League[] = [
  {
    id: "div1",
    name: "Division 1",
    slug: "division-1",
    seasonId: "season-1",
    order: 1,
    color: "#F59E0B",
    description: "トップディビジョン",
    maxTeams: 8,
  },
  {
    id: "div2",
    name: "Division 2",
    slug: "division-2",
    seasonId: "season-1",
    order: 2,
    color: "#8B5CF6",
    description: "",
    maxTeams: 8,
  },
  {
    id: "div3",
    name: "Division 3",
    slug: "division-3",
    seasonId: "season-1",
    order: 3,
    color: "#10B981",
    description: "",
    maxTeams: 8,
  },
  {
    id: "div4",
    name: "Division 4",
    slug: "division-4",
    seasonId: "season-1",
    order: 4,
    color: "#EF4444",
    description: "",
    maxTeams: 8,
  },
  {
    id: "div5",
    name: "Division 5",
    slug: "division-5",
    seasonId: "season-1",
    order: 5,
    color: "#3B82F6",
    description: "",
    maxTeams: 8,
  },
  {
    id: "div6",
    name: "Division 6",
    slug: "division-6",
    seasonId: "season-1",
    order: 6,
    color: "#EC4899",
    description: "",
    maxTeams: 8,
  },
];

export const MOCK_TEAMS: Team[] = [
  // Division 1
  {
    id: "t1-1",
    name: "博多キングス",
    slug: "hakata-kings",
    leagueId: "div1",
    leagueName: "Division 1",
    logoUrl: null,
    homeColor: "#F59E0B",
    captainName: "田中 海斗",
    description: "博多を拠点とする強豪チーム",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t1-2",
    name: "天神エース",
    slug: "tenjin-aces",
    leagueId: "div1",
    leagueName: "Division 1",
    logoUrl: null,
    homeColor: "#F59E0B",
    captainName: "山本 翔",
    description: "天神エリア代表",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t1-3",
    name: "中洲レジェンズ",
    slug: "nakasu-legends",
    leagueId: "div1",
    leagueName: "Division 1",
    logoUrl: null,
    homeColor: "#F59E0B",
    captainName: "佐藤 大輝",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t1-4",
    name: "福岡ブレイカーズ",
    slug: "fukuoka-breakers",
    leagueId: "div1",
    leagueName: "Division 1",
    logoUrl: null,
    homeColor: "#F59E0B",
    captainName: "鈴木 涼",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t1-5",
    name: "北九州ウォリアーズ",
    slug: "kitakyushu-warriors",
    leagueId: "div1",
    leagueName: "Division 1",
    logoUrl: null,
    homeColor: "#F59E0B",
    captainName: "高橋 誠",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t1-6",
    name: "大宰府サムライ",
    slug: "dazaifu-samurai",
    leagueId: "div1",
    leagueName: "Division 1",
    logoUrl: null,
    homeColor: "#F59E0B",
    captainName: "伊藤 健",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t1-7",
    name: "宗像ドラゴンズ",
    slug: "munakata-dragons",
    leagueId: "div1",
    leagueName: "Division 1",
    logoUrl: null,
    homeColor: "#F59E0B",
    captainName: "中村 陽",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t1-8",
    name: "糸島フェニックス",
    slug: "itoshima-phoenix",
    leagueId: "div1",
    leagueName: "Division 1",
    logoUrl: null,
    homeColor: "#F59E0B",
    captainName: "小林 蓮",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  // Division 2
  {
    id: "t2-1",
    name: "福岡スターズ",
    slug: "fukuoka-stars",
    leagueId: "div2",
    leagueName: "Division 2",
    logoUrl: null,
    homeColor: "#8B5CF6",
    captainName: "加藤 龍",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t2-2",
    name: "博多ロイヤルズ",
    slug: "hakata-royals",
    leagueId: "div2",
    leagueName: "Division 2",
    logoUrl: null,
    homeColor: "#8B5CF6",
    captainName: "吉田 光",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t2-3",
    name: "天神ナイツ",
    slug: "tenjin-knights",
    leagueId: "div2",
    leagueName: "Division 2",
    logoUrl: null,
    homeColor: "#8B5CF6",
    captainName: "山田 悠",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t2-4",
    name: "中洲クラウンズ",
    slug: "nakasu-crowns",
    leagueId: "div2",
    leagueName: "Division 2",
    logoUrl: null,
    homeColor: "#8B5CF6",
    captainName: "井上 颯",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t2-5",
    name: "福岡タイガース",
    slug: "fukuoka-tigers",
    leagueId: "div2",
    leagueName: "Division 2",
    logoUrl: null,
    homeColor: "#8B5CF6",
    captainName: "木村 岳",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t2-6",
    name: "北九州バルカンズ",
    slug: "kitakyushu-vulcans",
    leagueId: "div2",
    leagueName: "Division 2",
    logoUrl: null,
    homeColor: "#8B5CF6",
    captainName: "林 駿",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t2-7",
    name: "大宰府ライダーズ",
    slug: "dazaifu-riders",
    leagueId: "div2",
    leagueName: "Division 2",
    logoUrl: null,
    homeColor: "#8B5CF6",
    captainName: "清水 湊",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t2-8",
    name: "宗像ストライカーズ",
    slug: "munakata-strikers",
    leagueId: "div2",
    leagueName: "Division 2",
    logoUrl: null,
    homeColor: "#8B5CF6",
    captainName: "山口 蒼",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  // Division 3
  {
    id: "t3-1",
    name: "Hakata Bulls",
    slug: "hakata-bulls",
    leagueId: "div3",
    leagueName: "Division 3",
    logoUrl: null,
    homeColor: "#10B981",
    captainName: "松本 彩",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t3-2",
    name: "Tenjin Wolves",
    slug: "tenjin-wolves",
    leagueId: "div3",
    leagueName: "Division 3",
    logoUrl: null,
    homeColor: "#10B981",
    captainName: "中島 煌",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t3-3",
    name: "糸島スパークス",
    slug: "itoshima-sparks",
    leagueId: "div3",
    leagueName: "Division 3",
    logoUrl: null,
    homeColor: "#10B981",
    captainName: "岡田 碧",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t3-4",
    name: "飯塚ライオンズ",
    slug: "iizuka-lions",
    leagueId: "div3",
    leagueName: "Division 3",
    logoUrl: null,
    homeColor: "#10B981",
    captainName: "村上 太陽",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t3-5",
    name: "Nakasu Rooks",
    slug: "nakasu-rooks",
    leagueId: "div3",
    leagueName: "Division 3",
    logoUrl: null,
    homeColor: "#10B981",
    captainName: "長谷川 空",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t3-6",
    name: "宇美サンダース",
    slug: "umi-thunders",
    leagueId: "div3",
    leagueName: "Division 3",
    logoUrl: null,
    homeColor: "#10B981",
    captainName: "藤田 樹",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t3-7",
    name: "Dazaifu Blaze",
    slug: "dazaifu-blaze",
    leagueId: "div3",
    leagueName: "Division 3",
    logoUrl: null,
    homeColor: "#10B981",
    captainName: "小野 誠",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t3-8",
    name: "春日ジャガーズ",
    slug: "kasuga-jaguars",
    leagueId: "div3",
    leagueName: "Division 3",
    logoUrl: null,
    homeColor: "#10B981",
    captainName: "近藤 颯",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  // Division 4
  {
    id: "t4-1",
    name: "博多フレアーズ",
    slug: "hakata-flares",
    leagueId: "div4",
    leagueName: "Division 4",
    logoUrl: null,
    homeColor: "#EF4444",
    captainName: "石田 奏",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t4-2",
    name: "Fukuoka Foxes",
    slug: "fukuoka-foxes",
    leagueId: "div4",
    leagueName: "Division 4",
    logoUrl: null,
    homeColor: "#EF4444",
    captainName: "橋本 凛",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t4-3",
    name: "大牟田シャークス",
    slug: "omuta-sharks",
    leagueId: "div4",
    leagueName: "Division 4",
    logoUrl: null,
    homeColor: "#EF4444",
    captainName: "西村 湊",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t4-4",
    name: "Hakata Ghosts",
    slug: "hakata-ghosts",
    leagueId: "div4",
    leagueName: "Division 4",
    logoUrl: null,
    homeColor: "#EF4444",
    captainName: "太田 蒼",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t4-5",
    name: "久留米バイパーズ",
    slug: "kurume-vipers",
    leagueId: "div4",
    leagueName: "Division 4",
    logoUrl: null,
    homeColor: "#EF4444",
    captainName: "森田 葵",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t4-6",
    name: "Tenjin Rockets",
    slug: "tenjin-rockets",
    leagueId: "div4",
    leagueName: "Division 4",
    logoUrl: null,
    homeColor: "#EF4444",
    captainName: "原田 翼",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t4-7",
    name: "行橋イーグルス",
    slug: "yukuhashi-eagles",
    leagueId: "div4",
    leagueName: "Division 4",
    logoUrl: null,
    homeColor: "#EF4444",
    captainName: "田村 朔",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t4-8",
    name: "Munakata Mavericks",
    slug: "munakata-mavericks",
    leagueId: "div4",
    leagueName: "Division 4",
    logoUrl: null,
    homeColor: "#EF4444",
    captainName: "岸本 晴",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  // Division 5
  {
    id: "t5-1",
    name: "博多ランブラーズ",
    slug: "hakata-ramblers",
    leagueId: "div5",
    leagueName: "Division 5",
    logoUrl: null,
    homeColor: "#3B82F6",
    captainName: "上田 遥",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t5-2",
    name: "Fukuoka Nomads",
    slug: "fukuoka-nomads",
    leagueId: "div5",
    leagueName: "Division 5",
    logoUrl: null,
    homeColor: "#3B82F6",
    captainName: "永田 隼",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t5-3",
    name: "粕屋クラッシャーズ",
    slug: "kasuya-crushers",
    leagueId: "div5",
    leagueName: "Division 5",
    logoUrl: null,
    homeColor: "#3B82F6",
    captainName: "福田 蓮",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t5-4",
    name: "Hakata Spirits",
    slug: "hakata-spirits",
    leagueId: "div5",
    leagueName: "Division 5",
    logoUrl: null,
    homeColor: "#3B82F6",
    captainName: "丸山 悠",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t5-5",
    name: "福津スコーピオンズ",
    slug: "fukutsu-scorpions",
    leagueId: "div5",
    leagueName: "Division 5",
    logoUrl: null,
    homeColor: "#3B82F6",
    captainName: "杉山 陸",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t5-6",
    name: "Tenjin Titans",
    slug: "tenjin-titans",
    leagueId: "div5",
    leagueName: "Division 5",
    logoUrl: null,
    homeColor: "#3B82F6",
    captainName: "松田 朱",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t5-7",
    name: "宗像クロスボーンズ",
    slug: "munakata-crossbones",
    leagueId: "div5",
    leagueName: "Division 5",
    logoUrl: null,
    homeColor: "#3B82F6",
    captainName: "野口 彩",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t5-8",
    name: "Hakata Vibes",
    slug: "hakata-vibes",
    leagueId: "div5",
    leagueName: "Division 5",
    logoUrl: null,
    homeColor: "#3B82F6",
    captainName: "坂本 結",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  // Division 6
  {
    id: "t6-1",
    name: "博多ブロッサムズ",
    slug: "hakata-blossoms",
    leagueId: "div6",
    leagueName: "Division 6",
    logoUrl: null,
    homeColor: "#EC4899",
    captainName: "高木 莉",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t6-2",
    name: "Fukuoka Pinks",
    slug: "fukuoka-pinks",
    leagueId: "div6",
    leagueName: "Division 6",
    logoUrl: null,
    homeColor: "#EC4899",
    captainName: "菊池 空",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t6-3",
    name: "大野城フローラ",
    slug: "onojo-flora",
    leagueId: "div6",
    leagueName: "Division 6",
    logoUrl: null,
    homeColor: "#EC4899",
    captainName: "浜田 咲",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t6-4",
    name: "Tenjin Petals",
    slug: "tenjin-petals",
    leagueId: "div6",
    leagueName: "Division 6",
    logoUrl: null,
    homeColor: "#EC4899",
    captainName: "横山 綺",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t6-5",
    name: "春日プリンセス",
    slug: "kasuga-princess",
    leagueId: "div6",
    leagueName: "Division 6",
    logoUrl: null,
    homeColor: "#EC4899",
    captainName: "斉藤 楓",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t6-6",
    name: "Nakasu Gems",
    slug: "nakasu-gems",
    leagueId: "div6",
    leagueName: "Division 6",
    logoUrl: null,
    homeColor: "#EC4899",
    captainName: "渡辺 桜",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t6-7",
    name: "糸島ラベンダーズ",
    slug: "itoshima-lavenders",
    leagueId: "div6",
    leagueName: "Division 6",
    logoUrl: null,
    homeColor: "#EC4899",
    captainName: "中田 凪",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
  {
    id: "t6-8",
    name: "Hakata Roses",
    slug: "hakata-roses",
    leagueId: "div6",
    leagueName: "Division 6",
    logoUrl: null,
    homeColor: "#EC4899",
    captainName: "池田 音",
    description: "",
    twitterUrl: null,
    instagramUrl: null,
    isActive: true,
  },
];

// Division 1 の順位データ
export const MOCK_STANDINGS_DIV1: TeamStanding[] = [
  {
    rank: 1,
    teamId: "t1-1",
    teamName: "博多キングス",
    teamLogoUrl: null,
    totalPoints: 52,
    roundPoints: { 1: 14, 2: 11, 3: 14, 4: 13 },
  },
  {
    rank: 2,
    teamId: "t1-2",
    teamName: "天神エース",
    teamLogoUrl: null,
    totalPoints: 48,
    roundPoints: { 1: 11, 2: 14, 3: 11, 4: 12 },
  },
  {
    rank: 3,
    teamId: "t1-3",
    teamName: "中洲レジェンズ",
    teamLogoUrl: null,
    totalPoints: 41,
    roundPoints: { 1: 9, 2: 12, 3: 10, 4: 10 },
  },
  {
    rank: 4,
    teamId: "t1-4",
    teamName: "福岡ブレイカーズ",
    teamLogoUrl: null,
    totalPoints: 38,
    roundPoints: { 1: 12, 2: 9, 3: 8, 4: 9 },
  },
  {
    rank: 5,
    teamId: "t1-5",
    teamName: "北九州ウォリアーズ",
    teamLogoUrl: null,
    totalPoints: 33,
    roundPoints: { 1: 8, 2: 8, 3: 9, 4: 8 },
  },
  {
    rank: 6,
    teamId: "t1-6",
    teamName: "大宰府サムライ",
    teamLogoUrl: null,
    totalPoints: 27,
    roundPoints: { 1: 7, 2: 7, 3: 7, 4: 6 },
  },
  {
    rank: 7,
    teamId: "t1-7",
    teamName: "宗像ドラゴンズ",
    teamLogoUrl: null,
    totalPoints: 22,
    roundPoints: { 1: 6, 2: 6, 3: 5, 4: 5 },
  },
  {
    rank: 8,
    teamId: "t1-8",
    teamName: "糸島フェニックス",
    teamLogoUrl: null,
    totalPoints: 15,
    roundPoints: { 1: 5, 2: 5, 3: 3, 4: 2 },
  },
];

// Division 2〜6 の順位データ（簡略版）
export const MOCK_STANDINGS: Record<string, TeamStanding[]> = {
  div1: MOCK_STANDINGS_DIV1,
  div2: [
    {
      rank: 1,
      teamId: "t2-1",
      teamName: "福岡スターズ",
      teamLogoUrl: null,
      totalPoints: 49,
      roundPoints: { 1: 13, 2: 12, 3: 14, 4: 10 },
    },
    {
      rank: 2,
      teamId: "t2-2",
      teamName: "博多ロイヤルズ",
      teamLogoUrl: null,
      totalPoints: 45,
      roundPoints: { 1: 11, 2: 11, 3: 11, 4: 12 },
    },
    {
      rank: 3,
      teamId: "t2-3",
      teamName: "天神ナイツ",
      teamLogoUrl: null,
      totalPoints: 40,
      roundPoints: { 1: 10, 2: 13, 3: 9, 4: 8 },
    },
    {
      rank: 4,
      teamId: "t2-4",
      teamName: "中洲クラウンズ",
      teamLogoUrl: null,
      totalPoints: 36,
      roundPoints: { 1: 9, 2: 9, 3: 10, 4: 8 },
    },
    {
      rank: 5,
      teamId: "t2-5",
      teamName: "福岡タイガース",
      teamLogoUrl: null,
      totalPoints: 31,
      roundPoints: { 1: 8, 2: 8, 3: 8, 4: 7 },
    },
    {
      rank: 6,
      teamId: "t2-6",
      teamName: "北九州バルカンズ",
      teamLogoUrl: null,
      totalPoints: 26,
      roundPoints: { 1: 7, 2: 7, 3: 6, 4: 6 },
    },
    {
      rank: 7,
      teamId: "t2-7",
      teamName: "大宰府ライダーズ",
      teamLogoUrl: null,
      totalPoints: 20,
      roundPoints: { 1: 5, 2: 6, 3: 5, 4: 4 },
    },
    {
      rank: 8,
      teamId: "t2-8",
      teamName: "宗像ストライカーズ",
      teamLogoUrl: null,
      totalPoints: 14,
      roundPoints: { 1: 4, 2: 4, 3: 3, 4: 3 },
    },
  ],
  div3: [
    {
      rank: 1,
      teamId: "t3-1",
      teamName: "Hakata Bulls",
      teamLogoUrl: null,
      totalPoints: 46,
      roundPoints: { 1: 12, 2: 11, 3: 12, 4: 11 },
    },
    {
      rank: 2,
      teamId: "t3-2",
      teamName: "Tenjin Wolves",
      teamLogoUrl: null,
      totalPoints: 43,
      roundPoints: { 1: 11, 2: 13, 3: 10, 4: 9 },
    },
    {
      rank: 3,
      teamId: "t3-3",
      teamName: "糸島スパークス",
      teamLogoUrl: null,
      totalPoints: 38,
      roundPoints: { 1: 10, 2: 9, 3: 11, 4: 8 },
    },
    {
      rank: 4,
      teamId: "t3-4",
      teamName: "飯塚ライオンズ",
      teamLogoUrl: null,
      totalPoints: 34,
      roundPoints: { 1: 9, 2: 10, 3: 7, 4: 8 },
    },
    {
      rank: 5,
      teamId: "t3-5",
      teamName: "Nakasu Rooks",
      teamLogoUrl: null,
      totalPoints: 29,
      roundPoints: { 1: 7, 2: 7, 3: 8, 4: 7 },
    },
    {
      rank: 6,
      teamId: "t3-6",
      teamName: "宇美サンダース",
      teamLogoUrl: null,
      totalPoints: 24,
      roundPoints: { 1: 6, 2: 6, 3: 6, 4: 6 },
    },
    {
      rank: 7,
      teamId: "t3-7",
      teamName: "Dazaifu Blaze",
      teamLogoUrl: null,
      totalPoints: 18,
      roundPoints: { 1: 5, 2: 5, 3: 4, 4: 4 },
    },
    {
      rank: 8,
      teamId: "t3-8",
      teamName: "春日ジャガーズ",
      teamLogoUrl: null,
      totalPoints: 12,
      roundPoints: { 1: 3, 2: 4, 3: 3, 4: 2 },
    },
  ],
  div4: [
    {
      rank: 1,
      teamId: "t4-1",
      teamName: "博多フレアーズ",
      teamLogoUrl: null,
      totalPoints: 50,
      roundPoints: { 1: 13, 2: 12, 3: 13, 4: 12 },
    },
    {
      rank: 2,
      teamId: "t4-2",
      teamName: "Fukuoka Foxes",
      teamLogoUrl: null,
      totalPoints: 44,
      roundPoints: { 1: 11, 2: 11, 3: 11, 4: 11 },
    },
    {
      rank: 3,
      teamId: "t4-3",
      teamName: "大牟田シャークス",
      teamLogoUrl: null,
      totalPoints: 39,
      roundPoints: { 1: 10, 2: 10, 3: 9, 4: 10 },
    },
    {
      rank: 4,
      teamId: "t4-4",
      teamName: "Hakata Ghosts",
      teamLogoUrl: null,
      totalPoints: 35,
      roundPoints: { 1: 9, 2: 8, 3: 10, 4: 8 },
    },
    {
      rank: 5,
      teamId: "t4-5",
      teamName: "久留米バイパーズ",
      teamLogoUrl: null,
      totalPoints: 30,
      roundPoints: { 1: 8, 2: 7, 3: 7, 4: 8 },
    },
    {
      rank: 6,
      teamId: "t4-6",
      teamName: "Tenjin Rockets",
      teamLogoUrl: null,
      totalPoints: 25,
      roundPoints: { 1: 6, 2: 6, 3: 7, 4: 6 },
    },
    {
      rank: 7,
      teamId: "t4-7",
      teamName: "行橋イーグルス",
      teamLogoUrl: null,
      totalPoints: 19,
      roundPoints: { 1: 5, 2: 5, 3: 5, 4: 4 },
    },
    {
      rank: 8,
      teamId: "t4-8",
      teamName: "Munakata Mavericks",
      teamLogoUrl: null,
      totalPoints: 13,
      roundPoints: { 1: 3, 2: 3, 3: 4, 4: 3 },
    },
  ],
  div5: [
    {
      rank: 1,
      teamId: "t5-1",
      teamName: "博多ランブラーズ",
      teamLogoUrl: null,
      totalPoints: 47,
      roundPoints: { 1: 12, 2: 12, 3: 12, 4: 11 },
    },
    {
      rank: 2,
      teamId: "t5-2",
      teamName: "Fukuoka Nomads",
      teamLogoUrl: null,
      totalPoints: 42,
      roundPoints: { 1: 11, 2: 10, 3: 11, 4: 10 },
    },
    {
      rank: 3,
      teamId: "t5-3",
      teamName: "粕屋クラッシャーズ",
      teamLogoUrl: null,
      totalPoints: 37,
      roundPoints: { 1: 9, 2: 11, 3: 9, 4: 8 },
    },
    {
      rank: 4,
      teamId: "t5-4",
      teamName: "Hakata Spirits",
      teamLogoUrl: null,
      totalPoints: 33,
      roundPoints: { 1: 8, 2: 9, 3: 8, 4: 8 },
    },
    {
      rank: 5,
      teamId: "t5-5",
      teamName: "福津スコーピオンズ",
      teamLogoUrl: null,
      totalPoints: 28,
      roundPoints: { 1: 7, 2: 7, 3: 7, 4: 7 },
    },
    {
      rank: 6,
      teamId: "t5-6",
      teamName: "Tenjin Titans",
      teamLogoUrl: null,
      totalPoints: 22,
      roundPoints: { 1: 6, 2: 5, 3: 6, 4: 5 },
    },
    {
      rank: 7,
      teamId: "t5-7",
      teamName: "宗像クロスボーンズ",
      teamLogoUrl: null,
      totalPoints: 17,
      roundPoints: { 1: 4, 2: 6, 3: 4, 4: 3 },
    },
    {
      rank: 8,
      teamId: "t5-8",
      teamName: "Hakata Vibes",
      teamLogoUrl: null,
      totalPoints: 11,
      roundPoints: { 1: 3, 2: 3, 3: 3, 4: 2 },
    },
  ],
  div6: [
    {
      rank: 1,
      teamId: "t6-1",
      teamName: "博多ブロッサムズ",
      teamLogoUrl: null,
      totalPoints: 48,
      roundPoints: { 1: 12, 2: 12, 3: 13, 4: 11 },
    },
    {
      rank: 2,
      teamId: "t6-2",
      teamName: "Fukuoka Pinks",
      teamLogoUrl: null,
      totalPoints: 43,
      roundPoints: { 1: 11, 2: 11, 3: 11, 4: 10 },
    },
    {
      rank: 3,
      teamId: "t6-3",
      teamName: "大野城フローラ",
      teamLogoUrl: null,
      totalPoints: 38,
      roundPoints: { 1: 10, 2: 9, 3: 10, 4: 9 },
    },
    {
      rank: 4,
      teamId: "t6-4",
      teamName: "Tenjin Petals",
      teamLogoUrl: null,
      totalPoints: 34,
      roundPoints: { 1: 9, 2: 9, 3: 8, 4: 8 },
    },
    {
      rank: 5,
      teamId: "t6-5",
      teamName: "春日プリンセス",
      teamLogoUrl: null,
      totalPoints: 28,
      roundPoints: { 1: 7, 2: 7, 3: 7, 4: 7 },
    },
    {
      rank: 6,
      teamId: "t6-6",
      teamName: "Nakasu Gems",
      teamLogoUrl: null,
      totalPoints: 22,
      roundPoints: { 1: 6, 2: 6, 3: 5, 4: 5 },
    },
    {
      rank: 7,
      teamId: "t6-7",
      teamName: "糸島ラベンダーズ",
      teamLogoUrl: null,
      totalPoints: 16,
      roundPoints: { 1: 4, 2: 5, 3: 4, 4: 3 },
    },
    {
      rank: 8,
      teamId: "t6-8",
      teamName: "Hakata Roses",
      teamLogoUrl: null,
      totalPoints: 10,
      roundPoints: { 1: 3, 2: 3, 3: 2, 4: 2 },
    },
  ],
};

// スケジュール（全ディビジョン共通構造）
const VENUES = [
  "MEGA",
  "ポーカーラウンジ天神",
  "キャッシュゲームクラブ博多",
  "THE POKER HOUSE",
  "CHIP博多",
  "ポーカースタジアム",
];

export const MOCK_ROUNDS: Round[] = [
  // Division 1 rounds
  {
    id: "r1d1-1",
    name: "第1節",
    leagueId: "div1",
    leagueName: "Division 1",
    roundNumber: 1,
    date: "2026-03-01",
    venue: "MEGA",
    venueUrl: null,
    status: "finished",
    isPlayoff: false,
  },
  {
    id: "r1d1-2",
    name: "第2節",
    leagueId: "div1",
    leagueName: "Division 1",
    roundNumber: 2,
    date: "2026-03-08",
    venue: "MEGA",
    venueUrl: null,
    status: "finished",
    isPlayoff: false,
  },
  {
    id: "r1d1-3",
    name: "第3節",
    leagueId: "div1",
    leagueName: "Division 1",
    roundNumber: 3,
    date: "2026-03-15",
    venue: "MEGA",
    venueUrl: null,
    status: "finished",
    isPlayoff: false,
  },
  {
    id: "r1d1-4",
    name: "第4節",
    leagueId: "div1",
    leagueName: "Division 1",
    roundNumber: 4,
    date: "2026-03-22",
    venue: "MEGA",
    venueUrl: null,
    status: "finished",
    isPlayoff: false,
  },
  {
    id: "r1d1-5",
    name: "第5節",
    leagueId: "div1",
    leagueName: "Division 1",
    roundNumber: 5,
    date: "2026-03-28",
    venue: "MEGA",
    venueUrl: null,
    status: "next",
    isPlayoff: false,
  },
  ...Array.from({ length: 17 }, (_, i) => ({
    id: `r1d1-${i + 6}`,
    name: `第${i + 6}節`,
    leagueId: "div1",
    leagueName: "Division 1",
    roundNumber: i + 6,
    date: `2026-0${Math.floor((i + 2) / 4) + 4}-${String(((i % 4) + 1) * 7).padStart(2, "0")}`,
    venue: VENUES[i % VENUES.length],
    venueUrl: null,
    status: "scheduled" as const,
    isPlayoff: false,
  })),
  {
    id: "r1d1-wc",
    name: "WILD CARD",
    leagueId: "div1",
    leagueName: "Division 1",
    roundNumber: 23,
    date: "2026-08-08",
    venue: "MEGA",
    venueUrl: null,
    status: "scheduled",
    isPlayoff: true,
  },
  {
    id: "r1d1-sf",
    name: "SEMI FINAL",
    leagueId: "div1",
    leagueName: "Division 1",
    roundNumber: 24,
    date: "2026-08-16",
    venue: "MEGA",
    venueUrl: null,
    status: "scheduled",
    isPlayoff: true,
  },
  {
    id: "r1d1-f",
    name: "THE FINAL",
    leagueId: "div1",
    leagueName: "Division 1",
    roundNumber: 25,
    date: "2026-08-30",
    venue: "MEGA",
    venueUrl: null,
    status: "scheduled",
    isPlayoff: true,
  },
  // Division 2 rounds（簡略）
  {
    id: "r2d2-1",
    name: "第1節",
    leagueId: "div2",
    leagueName: "Division 2",
    roundNumber: 1,
    date: "2026-03-02",
    venue: "ポーカーラウンジ天神",
    venueUrl: null,
    status: "finished",
    isPlayoff: false,
  },
  {
    id: "r2d2-2",
    name: "第2節",
    leagueId: "div2",
    leagueName: "Division 2",
    roundNumber: 2,
    date: "2026-03-09",
    venue: "ポーカーラウンジ天神",
    venueUrl: null,
    status: "finished",
    isPlayoff: false,
  },
  {
    id: "r2d2-3",
    name: "第3節",
    leagueId: "div2",
    leagueName: "Division 2",
    roundNumber: 3,
    date: "2026-03-16",
    venue: "ポーカーラウンジ天神",
    venueUrl: null,
    status: "finished",
    isPlayoff: false,
  },
  {
    id: "r2d2-4",
    name: "第4節",
    leagueId: "div2",
    leagueName: "Division 2",
    roundNumber: 4,
    date: "2026-03-23",
    venue: "ポーカーラウンジ天神",
    venueUrl: null,
    status: "finished",
    isPlayoff: false,
  },
  {
    id: "r2d2-5",
    name: "第5節",
    leagueId: "div2",
    leagueName: "Division 2",
    roundNumber: 5,
    date: "2026-03-29",
    venue: "ポーカーラウンジ天神",
    venueUrl: null,
    status: "next",
    isPlayoff: false,
  },
  ...Array.from({ length: 17 }, (_, i) => ({
    id: `r2d2-${i + 6}`,
    name: `第${i + 6}節`,
    leagueId: "div2",
    leagueName: "Division 2",
    roundNumber: i + 6,
    date: `2026-04-${String((i + 1) * 6).padStart(2, "0")}`,
    venue: "ポーカーラウンジ天神",
    venueUrl: null,
    status: "scheduled" as const,
    isPlayoff: false,
  })),
  {
    id: "r2d2-wc",
    name: "WILD CARD",
    leagueId: "div2",
    leagueName: "Division 2",
    roundNumber: 23,
    date: "2026-08-09",
    venue: "ポーカーラウンジ天神",
    venueUrl: null,
    status: "scheduled",
    isPlayoff: true,
  },
  {
    id: "r2d2-sf",
    name: "SEMI FINAL",
    leagueId: "div2",
    leagueName: "Division 2",
    roundNumber: 24,
    date: "2026-08-17",
    venue: "ポーカーラウンジ天神",
    venueUrl: null,
    status: "scheduled",
    isPlayoff: true,
  },
  {
    id: "r2d2-f",
    name: "THE FINAL",
    leagueId: "div2",
    leagueName: "Division 2",
    roundNumber: 25,
    date: "2026-08-31",
    venue: "ポーカーラウンジ天神",
    venueUrl: null,
    status: "scheduled",
    isPlayoff: true,
  },
  // Division 3〜6 は代表的なデータのみ
  ...["div3", "div4", "div5", "div6"].flatMap((divId, divIdx) => {
    const divNum = divIdx + 3;
    const venue = VENUES[(divIdx + 2) % VENUES.length];
    const leagueName = `Division ${divNum}`;
    return [
      {
        id: `r${divNum}d${divNum}-1`,
        name: "第1節",
        leagueId: divId,
        leagueName,
        roundNumber: 1,
        date: `2026-03-0${divIdx + 3}`,
        venue,
        venueUrl: null,
        status: "finished" as const,
        isPlayoff: false,
      },
      {
        id: `r${divNum}d${divNum}-2`,
        name: "第2節",
        leagueId: divId,
        leagueName,
        roundNumber: 2,
        date: `2026-03-1${divIdx}`,
        venue,
        venueUrl: null,
        status: "finished" as const,
        isPlayoff: false,
      },
      {
        id: `r${divNum}d${divNum}-3`,
        name: "第3節",
        leagueId: divId,
        leagueName,
        roundNumber: 3,
        date: `2026-03-1${divIdx + 7}`,
        venue,
        venueUrl: null,
        status: "finished" as const,
        isPlayoff: false,
      },
      {
        id: `r${divNum}d${divNum}-4`,
        name: "第4節",
        leagueId: divId,
        leagueName,
        roundNumber: 4,
        date: `2026-03-2${divIdx + 4}`,
        venue,
        venueUrl: null,
        status: "finished" as const,
        isPlayoff: false,
      },
      {
        id: `r${divNum}d${divNum}-5`,
        name: "第5節",
        leagueId: divId,
        leagueName,
        roundNumber: 5,
        date: "2026-03-30",
        venue,
        venueUrl: null,
        status: "next" as const,
        isPlayoff: false,
      },
      ...Array.from({ length: 17 }, (_, i) => ({
        id: `r${divNum}d${divNum}-${i + 6}`,
        name: `第${i + 6}節`,
        leagueId: divId,
        leagueName,
        roundNumber: i + 6,
        date: `2026-05-${String((i + 1) * 6).padStart(2, "0")}`,
        venue,
        venueUrl: null,
        status: "scheduled" as const,
        isPlayoff: false,
      })),
      {
        id: `r${divNum}d${divNum}-wc`,
        name: "WILD CARD",
        leagueId: divId,
        leagueName,
        roundNumber: 23,
        date: "2026-08-10",
        venue,
        venueUrl: null,
        status: "scheduled" as const,
        isPlayoff: true,
      },
      {
        id: `r${divNum}d${divNum}-sf`,
        name: "SEMI FINAL",
        leagueId: divId,
        leagueName,
        roundNumber: 24,
        date: "2026-08-18",
        venue,
        venueUrl: null,
        status: "scheduled" as const,
        isPlayoff: true,
      },
      {
        id: `r${divNum}d${divNum}-f`,
        name: "THE FINAL",
        leagueId: divId,
        leagueName,
        roundNumber: 25,
        date: "2026-08-31",
        venue,
        venueUrl: null,
        status: "scheduled" as const,
        isPlayoff: true,
      },
    ];
  }),
];

export const MOCK_NEWS: NewsItem[] = [
  {
    id: "n1",
    title: "第4節 結果発表 — 博多キングスが首位守る",
    slug: "round-4-results",
    category: "結果",
    publishedAt: "2026.03.24",
    thumbnailUrl: null,
    body: `第4節が2026年3月22日（日）にMEGAにて開催されました。

Division 1では博多キングスが13ポイントを獲得し、首位をキープ。天神エースが12ポイントで2位につけ、両者の差は縮まりつつあります。

**Division 1 第4節結果**
1位: 博多キングス — 13pt（累計52pt）
2位: 天神エース — 12pt（累計48pt）
3位: 中洲レジェンズ — 10pt（累計41pt）
4位: 福岡ブレイカーズ — 9pt（累計38pt）
5位: 北九州ウォリアーズ — 8pt（累計33pt）
6位: 大宰府サムライ — 6pt（累計27pt）
7位: 宗像ドラゴンズ — 5pt（累計22pt）
8位: 糸島フェニックス — 2pt（累計15pt）

次節（第5節）は2026年3月28日（土）に開催予定です。`,
    isPublished: true,
    seasonId: "season-1",
  },
  {
    id: "n2",
    title: "第3節 MVP インタビュー — 天神エース 山本翔選手",
    slug: "round-3-mvp-interview",
    category: "お知らせ",
    publishedAt: "2026.03.17",
    thumbnailUrl: null,
    body: `第3節でMVPを獲得した天神エースの山本翔選手にインタビューを行いました。

**Q: 第3節の振り返りをお願いします。**

A: 序盤からアグレッシブにプレーできました。重要なポットでしっかりと判断できたことが、今回の結果につながったと思います。

**Q: チームとしての目標は？**

A: Division 1の優勝はもちろんですが、まずは一節一節を大切に戦っていきたいです。博多キングスとの差を縮めていきたいと思っています。

**Q: ファンへのメッセージ**

A: いつも応援ありがとうございます。FSLをもっと盛り上げていけるよう、全力で戦います！`,
    isPublished: true,
    seasonId: "season-1",
  },
  {
    id: "n3",
    title: "Season 1 第3節が終了。順位変動に注目！",
    slug: "round-3-report",
    category: "結果",
    publishedAt: "2026.03.17",
    thumbnailUrl: null,
    body: `2026年3月15日（日）に第3節が開催されました。全6ディビジョンで熱戦が繰り広げられました。

**主なトピック**
- Division 1: 博多キングスが3連勝で首位独走
- Division 2: 福岡スターズが依然トップをキープ
- Division 3: 上位4チームが接戦

レギュラーシーズンは残り19節。プレーオフ進出ラインの争いはまだまだ激しくなりそうです。`,
    isPublished: true,
    seasonId: "season-1",
  },
  {
    id: "n4",
    title: "第2節 結果発表 — 各ディビジョンの展開",
    slug: "round-2-results",
    category: "結果",
    publishedAt: "2026.03.10",
    thumbnailUrl: null,
    body: `第2節が2026年3月8日（日）に開催されました。

今節は各ディビジョンで波乱の展開も見られました。Division 2では上位チームが接戦を繰り広げ、今後の行方が注目されます。

**Division 1 第2節ハイライト**
天神エースが今節トップの14ポイントを獲得し、首位との差を縮めました。後半戦に向けて上位争いがさらに激化しそうです。`,
    isPublished: true,
    seasonId: "season-1",
  },
  {
    id: "n5",
    title: "FSL Season 1 いよいよ開幕！",
    slug: "season-1-kickoff",
    category: "イベント",
    publishedAt: "2026.03.01",
    thumbnailUrl: null,
    body: `Fukuoka Super League（FSL）のSeason 1がついに開幕しました！

今シーズンは6ディビジョン・48チームが参加する、過去最大規模のリーグ戦となります。

**開催概要**
- 期間: 2026年3月〜8月
- 参加: 6ディビジョン × 8チーム = 計48チーム
- 節数: 全22節 + プレーオフ（WILD CARD / SEMI FINAL / THE FINAL）
- 会場: MEGA・ポーカーラウンジ天神・他

全チームの健闘を心よりお祈りしています。今シーズンも熱い戦いにご期待ください！`,
    isPublished: true,
    seasonId: "season-1",
  },
  {
    id: "n6",
    title: "FSL Season 1 参加チーム募集終了のお知らせ",
    slug: "team-registration-closed",
    category: "お知らせ",
    publishedAt: "2026.02.15",
    thumbnailUrl: null,
    body: `FSL Season 1への参加チーム募集が定員に達したため、募集を終了しました。

多数のご応募をいただき、誠にありがとうございました。今シーズンは48チームでの開催となります。

次回シーズン（Season 2）の参加募集は2026年秋頃を予定しています。最新情報は公式SNSをご確認ください。`,
    isPublished: true,
    seasonId: "season-1",
  },
];

export interface MatchResult {
  roundId: string;
  leagueId: string;
  roundNumber: number;
  results: Array<{
    rank: number;
    teamId: string;
    teamName: string;
    points: number;
  }>;
}

export const MOCK_MATCH_RESULTS: MatchResult[] = [
  {
    roundId: "r1d1-1",
    leagueId: "div1",
    roundNumber: 1,
    results: [
      { rank: 1, teamId: "t1-1", teamName: "博多キングス", points: 14 },
      { rank: 2, teamId: "t1-4", teamName: "福岡ブレイカーズ", points: 12 },
      { rank: 3, teamId: "t1-2", teamName: "天神エース", points: 11 },
      { rank: 4, teamId: "t1-3", teamName: "中洲レジェンズ", points: 9 },
      { rank: 5, teamId: "t1-5", teamName: "北九州ウォリアーズ", points: 8 },
      { rank: 6, teamId: "t1-6", teamName: "大宰府サムライ", points: 7 },
      { rank: 7, teamId: "t1-7", teamName: "宗像ドラゴンズ", points: 6 },
      { rank: 8, teamId: "t1-8", teamName: "糸島フェニックス", points: 5 },
    ],
  },
  {
    roundId: "r1d1-2",
    leagueId: "div1",
    roundNumber: 2,
    results: [
      { rank: 1, teamId: "t1-2", teamName: "天神エース", points: 14 },
      { rank: 2, teamId: "t1-3", teamName: "中洲レジェンズ", points: 12 },
      { rank: 3, teamId: "t1-1", teamName: "博多キングス", points: 11 },
      { rank: 4, teamId: "t1-4", teamName: "福岡ブレイカーズ", points: 9 },
      { rank: 5, teamId: "t1-5", teamName: "北九州ウォリアーズ", points: 8 },
      { rank: 6, teamId: "t1-6", teamName: "大宰府サムライ", points: 7 },
      { rank: 7, teamId: "t1-7", teamName: "宗像ドラゴンズ", points: 6 },
      { rank: 8, teamId: "t1-8", teamName: "糸島フェニックス", points: 5 },
    ],
  },
  {
    roundId: "r1d1-3",
    leagueId: "div1",
    roundNumber: 3,
    results: [
      { rank: 1, teamId: "t1-1", teamName: "博多キングス", points: 14 },
      { rank: 2, teamId: "t1-2", teamName: "天神エース", points: 11 },
      { rank: 3, teamId: "t1-3", teamName: "中洲レジェンズ", points: 10 },
      { rank: 4, teamId: "t1-5", teamName: "北九州ウォリアーズ", points: 9 },
      { rank: 5, teamId: "t1-4", teamName: "福岡ブレイカーズ", points: 8 },
      { rank: 6, teamId: "t1-6", teamName: "大宰府サムライ", points: 7 },
      { rank: 7, teamId: "t1-7", teamName: "宗像ドラゴンズ", points: 5 },
      { rank: 8, teamId: "t1-8", teamName: "糸島フェニックス", points: 3 },
    ],
  },
  {
    roundId: "r1d1-4",
    leagueId: "div1",
    roundNumber: 4,
    results: [
      { rank: 1, teamId: "t1-1", teamName: "博多キングス", points: 13 },
      { rank: 2, teamId: "t1-2", teamName: "天神エース", points: 12 },
      { rank: 3, teamId: "t1-3", teamName: "中洲レジェンズ", points: 10 },
      { rank: 4, teamId: "t1-4", teamName: "福岡ブレイカーズ", points: 9 },
      { rank: 5, teamId: "t1-5", teamName: "北九州ウォリアーズ", points: 8 },
      { rank: 6, teamId: "t1-6", teamName: "大宰府サムライ", points: 6 },
      { rank: 7, teamId: "t1-7", teamName: "宗像ドラゴンズ", points: 5 },
      { rank: 8, teamId: "t1-8", teamName: "糸島フェニックス", points: 2 },
    ],
  },
];

export const MOCK_ARCHIVE: ArchiveSeason[] = [];

export const MOCK_CHAMPIONS = [
  {
    season: "Season 1",
    year: "2026",
    div1: "—（進行中）",
    div2: "—",
    div3: "—",
    div4: "—",
    div5: "—",
    div6: "—",
    status: "active",
  },
];
